require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'derleng' do
config = use_native_modules!

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNQrGenerator', :path => '../node_modules/rn-qr-generator'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'derlengTests' do
    inherit! :complete
    # Pods for testing
  end

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'derleng-tvOS' do
  # Pods for derleng-tvOS

  target 'derleng-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
